CXX = g++
CXXFLAGS = -std=c++17 -Wall \
    -Ilib/Crow/include \
    -Ilib/asio/asio/include \
    -Ilib/jwt-cpp/include \
    -Isrc \
    -I/usr/local/include

LDFLAGS = -L/usr/local/lib \
    -lpthread -lpqxx -lpq -lssl -lcrypto

SRC = src/main.cpp
TARGET = crow_app

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC) $(LDFLAGS)

clean:
	rm -f $(TARGET)

.PHONY: all clean
